//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LayerCake.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LayerCake.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свойство &apos;{0}.{1}&apos; не доступно для чтения..
        /// </summary>
        internal static string RP_PropertyCannotBeRead {
            get {
                return ResourceManager.GetString("RP_PropertyCannotBeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свойство &apos;{0}.{1}&apos; не доступно для записи..
        /// </summary>
        internal static string RP_PropertyCannotBeWritten {
            get {
                return ResourceManager.GetString("RP_PropertyCannotBeWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция не выполнена. Пользователю, который указан в настройках подключения, запрещено выполнение запрошенной операции..
        /// </summary>
        internal static string VME_AccessDeniedException {
            get {
                return ResourceManager.GetString("VME_AccessDeniedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция не выполнена. Проверьте корректность строки подключения к сервису..
        /// </summary>
        internal static string VME_EndpointNotFoundException {
            get {
                return ResourceManager.GetString("VME_EndpointNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция не выполнена. Проверьте корректность имени пользователя, пароля или сертификата..
        /// </summary>
        internal static string VME_MessageSecurityException {
            get {
                return ResourceManager.GetString("VME_MessageSecurityException", resourceCulture);
            }
        }
    }
}
