//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LayerCake.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LayerCake.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание приложения..
        /// </summary>
        internal static string AB_CreatingApplication {
            get {
                return ResourceManager.GetString("AB_CreatingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание каталога уровня приложения..
        /// </summary>
        internal static string AB_CreatingApplicationCatalog {
            get {
                return ResourceManager.GetString("AB_CreatingApplicationCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание модели представления уровня приложения..
        /// </summary>
        internal static string AB_CreatingApplicationViewModel {
            get {
                return ResourceManager.GetString("AB_CreatingApplicationViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение LayerCake..
        /// </summary>
        internal static string AB_LayerCakeHello {
            get {
                return ResourceManager.GetString("AB_LayerCakeHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек главного окна приложения..
        /// </summary>
        internal static string AB_LoadingMainWindowsSettings {
            get {
                return ResourceManager.GetString("AB_LoadingMainWindowsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение приложения..
        /// </summary>
        internal static string AB_Running {
            get {
                return ResourceManager.GetString("AB_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение настроек главного окна приложения..
        /// </summary>
        internal static string AB_SavingWindowSettings {
            get {
                return ResourceManager.GetString("AB_SavingWindowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображение главного окна приложения..
        /// </summary>
        internal static string AB_ShowingMainWindow {
            get {
                return ResourceManager.GetString("AB_ShowingMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало работы приложения..
        /// </summary>
        internal static string AB_Starting {
            get {
                return ResourceManager.GetString("AB_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершение работы приложения..
        /// </summary>
        internal static string AB_Stopping {
            get {
                return ResourceManager.GetString("AB_Stopping", resourceCulture);
            }
        }
    }
}
